Search.appendIndex(
    [
                {
            "fqsen": "\\Collecthor\\FlySystem\\AddPrefixAdapter",
            "name": "AddPrefixAdapter",
            "summary": "Adds\u0020a\u0020prefix\u0020to\u0020all\u0020paths\u0020given\u0020to\u0020the\u0020adapter.",
            "url": "classes/Collecthor-FlySystem-AddPrefixAdapter.html"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\AddPrefixAdapter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-AddPrefixAdapter.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\AddPrefixAdapter\u003A\u003ApreparePath\u0028\u0029",
            "name": "preparePath",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-AddPrefixAdapter.html#method_preparePath"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\AddPrefixAdapter\u003A\u003AlistContents\u0028\u0029",
            "name": "listContents",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-AddPrefixAdapter.html#method_listContents"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\AddPrefixAdapter\u003A\u003AgetAdapter\u0028\u0029",
            "name": "getAdapter",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-AddPrefixAdapter.html#method_getAdapter"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\AddPrefixAdapter\u003A\u003A\u0024pathPrefixer",
            "name": "pathPrefixer",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-AddPrefixAdapter.html#property_pathPrefixer"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\AddPrefixAdapter\u003A\u003A\u0024base",
            "name": "base",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-AddPrefixAdapter.html#property_base"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\DirectoryViaPlaceholderFileAdapter",
            "name": "DirectoryViaPlaceholderFileAdapter",
            "summary": "Implements\u0020directory\u0020support\u0020for\u0020any\u0020adapter\u0020utilizing\u0020a\u0020placeholder\u0020file.",
            "url": "classes/Collecthor-FlySystem-DirectoryViaPlaceholderFileAdapter.html"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\DirectoryViaPlaceholderFileAdapter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-DirectoryViaPlaceholderFileAdapter.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\DirectoryViaPlaceholderFileAdapter\u003A\u003AgetAdapter\u0028\u0029",
            "name": "getAdapter",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-DirectoryViaPlaceholderFileAdapter.html#method_getAdapter"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\DirectoryViaPlaceholderFileAdapter\u003A\u003AcreateDirectory\u0028\u0029",
            "name": "createDirectory",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-DirectoryViaPlaceholderFileAdapter.html#method_createDirectory"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\DirectoryViaPlaceholderFileAdapter\u003A\u003AdirectoryExists\u0028\u0029",
            "name": "directoryExists",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-DirectoryViaPlaceholderFileAdapter.html#method_directoryExists"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\DirectoryViaPlaceholderFileAdapter\u003A\u003AlistContents\u0028\u0029",
            "name": "listContents",
            "summary": "Iteration\u0020will\u0020usually\u0020support\u0020directories\u0020even\u0020on\u0020adapters\u0020that\u0020don\u0027t\u0020have\u0020that\u0020concept.",
            "url": "classes/Collecthor-FlySystem-DirectoryViaPlaceholderFileAdapter.html#method_listContents"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\DirectoryViaPlaceholderFileAdapter\u003A\u003A\u0024base",
            "name": "base",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-DirectoryViaPlaceholderFileAdapter.html#property_base"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\DirectoryViaPlaceholderFileAdapter\u003A\u003A\u0024placeHolderName",
            "name": "placeHolderName",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-DirectoryViaPlaceholderFileAdapter.html#property_placeHolderName"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\IndirectAdapter",
            "name": "IndirectAdapter",
            "summary": "Indirect\u0020adapter\u0020implements\u0020a\u0020simple\u0020pattern\u0020that\u0020allows\u0020extending\u0020classes\u0020to\u0020provide\u0020a\u0020concrete\u0020adapter\u0020for\u0020any\u0020call\nas\u0020well\u0020as\u0020rewrite\u0020the\u0020path\u0020passed\u0020to\u0020such\u0020calls.",
            "url": "classes/Collecthor-FlySystem-IndirectAdapter.html"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\IndirectAdapter\u003A\u003ApreparePath\u0028\u0029",
            "name": "preparePath",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-IndirectAdapter.html#method_preparePath"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\IndirectAdapter\u003A\u003AgetAdapter\u0028\u0029",
            "name": "getAdapter",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-IndirectAdapter.html#method_getAdapter"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\IndirectAdapter\u003A\u003AfileExists\u0028\u0029",
            "name": "fileExists",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-IndirectAdapter.html#method_fileExists"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\IndirectAdapter\u003A\u003AdirectoryExists\u0028\u0029",
            "name": "directoryExists",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-IndirectAdapter.html#method_directoryExists"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\IndirectAdapter\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-IndirectAdapter.html#method_write"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\IndirectAdapter\u003A\u003AwriteStream\u0028\u0029",
            "name": "writeStream",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-IndirectAdapter.html#method_writeStream"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\IndirectAdapter\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-IndirectAdapter.html#method_read"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\IndirectAdapter\u003A\u003AreadStream\u0028\u0029",
            "name": "readStream",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-IndirectAdapter.html#method_readStream"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\IndirectAdapter\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-IndirectAdapter.html#method_delete"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\IndirectAdapter\u003A\u003AdeleteDirectory\u0028\u0029",
            "name": "deleteDirectory",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-IndirectAdapter.html#method_deleteDirectory"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\IndirectAdapter\u003A\u003AcreateDirectory\u0028\u0029",
            "name": "createDirectory",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-IndirectAdapter.html#method_createDirectory"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\IndirectAdapter\u003A\u003AsetVisibility\u0028\u0029",
            "name": "setVisibility",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-IndirectAdapter.html#method_setVisibility"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\IndirectAdapter\u003A\u003Avisibility\u0028\u0029",
            "name": "visibility",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-IndirectAdapter.html#method_visibility"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\IndirectAdapter\u003A\u003AmimeType\u0028\u0029",
            "name": "mimeType",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-IndirectAdapter.html#method_mimeType"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\IndirectAdapter\u003A\u003AlastModified\u0028\u0029",
            "name": "lastModified",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-IndirectAdapter.html#method_lastModified"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\IndirectAdapter\u003A\u003AfileSize\u0028\u0029",
            "name": "fileSize",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-IndirectAdapter.html#method_fileSize"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\IndirectAdapter\u003A\u003AlistContents\u0028\u0029",
            "name": "listContents",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-IndirectAdapter.html#method_listContents"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\IndirectAdapter\u003A\u003Amove\u0028\u0029",
            "name": "move",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-IndirectAdapter.html#method_move"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\IndirectAdapter\u003A\u003Acopy\u0028\u0029",
            "name": "copy",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-IndirectAdapter.html#method_copy"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\OverlayAdapter",
            "name": "OverlayAdapter",
            "summary": "This\u0020adapter\u0020mounts\u0020one\u0020adapter\u0020as\u0020an\u0020overlay\u0020on\u0020top\u0020of\u0020another\u0020based\u0020on\u0020a\u0020prefix",
            "url": "classes/Collecthor-FlySystem-OverlayAdapter.html"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\OverlayAdapter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-OverlayAdapter.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\OverlayAdapter\u003A\u003AgetAdapter\u0028\u0029",
            "name": "getAdapter",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-OverlayAdapter.html#method_getAdapter"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\OverlayAdapter\u003A\u003AlistContents\u0028\u0029",
            "name": "listContents",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-OverlayAdapter.html#method_listContents"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\OverlayAdapter\u003A\u003AcheckSourceAdapterMatchesDestination\u0028\u0029",
            "name": "checkSourceAdapterMatchesDestination",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-OverlayAdapter.html#method_checkSourceAdapterMatchesDestination"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\OverlayAdapter\u003A\u003Amove\u0028\u0029",
            "name": "move",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-OverlayAdapter.html#method_move"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\OverlayAdapter\u003A\u003AdeleteDirectory\u0028\u0029",
            "name": "deleteDirectory",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-OverlayAdapter.html#method_deleteDirectory"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\OverlayAdapter\u003A\u003AdirectoryExists\u0028\u0029",
            "name": "directoryExists",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-OverlayAdapter.html#method_directoryExists"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\OverlayAdapter\u003A\u003Acopy\u0028\u0029",
            "name": "copy",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-OverlayAdapter.html#method_copy"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\OverlayAdapter\u003A\u003A\u0024pathPrefixer",
            "name": "pathPrefixer",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-OverlayAdapter.html#property_pathPrefixer"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\OverlayAdapter\u003A\u003A\u0024overlay",
            "name": "overlay",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-OverlayAdapter.html#property_overlay"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\OverlayAdapter\u003A\u003A\u0024virtualDirectories",
            "name": "virtualDirectories",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-OverlayAdapter.html#property_virtualDirectories"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\OverlayAdapter\u003A\u003A\u0024base",
            "name": "base",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-OverlayAdapter.html#property_base"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\OverlayAdapter\u003A\u003A\u0024prefix",
            "name": "prefix",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-OverlayAdapter.html#property_prefix"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\StripPrefixAdapter",
            "name": "StripPrefixAdapter",
            "summary": "Strips\u0020a\u0020prefix\u0020from\u0020all\u0020paths\u0020given\u0020to\u0020the\u0020adapter.",
            "url": "classes/Collecthor-FlySystem-StripPrefixAdapter.html"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\StripPrefixAdapter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-StripPrefixAdapter.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\StripPrefixAdapter\u003A\u003ApreparePath\u0028\u0029",
            "name": "preparePath",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-StripPrefixAdapter.html#method_preparePath"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\StripPrefixAdapter\u003A\u003AlistContents\u0028\u0029",
            "name": "listContents",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-StripPrefixAdapter.html#method_listContents"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\StripPrefixAdapter\u003A\u003AgetAdapter\u0028\u0029",
            "name": "getAdapter",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-StripPrefixAdapter.html#method_getAdapter"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\StripPrefixAdapter\u003A\u003A\u0024pathPrefixer",
            "name": "pathPrefixer",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-StripPrefixAdapter.html#property_pathPrefixer"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\StripPrefixAdapter\u003A\u003A\u0024base",
            "name": "base",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-StripPrefixAdapter.html#property_base"
        },                {
            "fqsen": "\\Collecthor\\FlySystem\\StripPrefixAdapter\u003A\u003A\u0024prefix",
            "name": "prefix",
            "summary": "",
            "url": "classes/Collecthor-FlySystem-StripPrefixAdapter.html#property_prefix"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Collecthor\\FlySystem",
            "name": "FlySystem",
            "summary": "",
            "url": "namespaces/collecthor-flysystem.html"
        },                {
            "fqsen": "\\Collecthor",
            "name": "Collecthor",
            "summary": "",
            "url": "namespaces/collecthor.html"
        }            ]
);
