name: Automated releases
on:
  push:
    branches:
      - master
jobs:
  code_checks:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - uses: ramsey/composer-install@v3
      - name: Test code style
        run: vendor/bin/ecs
      - name: Static analysis
        run: vendor/bin/phpstan
      - name: Tests
        run: vendor/bin/phpunit --coverage-clover coverage.xml
      - name: Generate docs
        run: docker run --rm -v ${PWD}:/data phpdoc/phpdoc:3
      - name: Deploy docs to pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
      - uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
  release:
    permissions:
      issues: write
      packages: write
      contents: write
    name: Automated release
    needs: [code_checks]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: >
          npx
          -p "@semantic-release/commit-analyzer"
          -p "@semantic-release/release-notes-generator"
          -p conventional-changelog-conventionalcommits@6
          -p semantic-release
          -- semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
